server:
  port: ${BACKEND_PORT:8080} # default 8080, can be overridden by env var BACKEND_PORT

spring:
  application:
    name: student-activity

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:student_activity_tracker}
    username: ${DB_USER:raayaay}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    locations: classpath:db/migration

gg:
  jte:
    development-mode: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000
